### ISSUE TITLE
IBInspectable

### ISSUE THREAD

**Issue by Z-JaDe** [liuzhiyi1992/ZYCornerRadius#12]
建议加上IBInspectable特性支持，要不然在storyboard中的imageView圆角设置太麻烦了

**Comment by liuzhiyi1992** [comment]
抱歉最近比较忙，感谢朋友这个不错的建议，空闲下来我会留时间处理 : )

**Comment by liuzhiyi1992** [comment]
<img width="278" alt="2016-06-11 11 02 27" src="https://cloud.githubusercontent.com/assets/13046550/15989581/09caeeb8-30ad-11e6-9b8e-cc96b6f16212.png">
已经新增分支IBInspectable_v1.0，增加IB功能，方便在storyBoard直接设置圆角属性，不过因为category的关系，所有的UIImageView在IB中都会有属性编辑栏，有少许视觉污染。: )
