### ISSUE TITLE
设置UIViewContentModeScaleAspectFill的效果跟预想效果不同

### ISSUE THREAD

**Issue by caijunrong** [liuzhiyi1992/ZYCornerRadius#13]
当图片需要裁剪的时候，设置了图片的UIViewContentModeScaleAspectFill属性，但是结果只是简单的压缩了图片，并没有裁剪中间的那部分进行显示

**Comment by liuzhiyi1992** [comment]
已经处理并更新v0.9.2，非常感谢提出问题！ : )
