### ISSUE TITLE
为什么一开始显示圆形，但是如果重新setImageWithURL这样加载一下图片的 会变成原来的样子

### ISSUE THREAD

**Issue by xuehaoleng** [liuzhiyi1992/ZYCornerRadius#14]
具体表现在UITableview的复用上

[_portraitimag setImageWithURL:[NSURL URLWithString:url] placeholderImage:[UIImage imageNamed:@"defalut_logo"]options:SDWebImageRetryFailed];

**Comment by liuzhiyi1992** [comment]
最新版0.9.2会有这个问题，可以先使用旧版。这边会尽快处理

**Comment by liuzhiyi1992** [comment]
已处理。pod更新0.9.3版本，谢谢朋友提出
