### ISSUE TITLE
可以不用方法交换吗？

### ISSUE THREAD

**Issue by crespoxiao** [liuzhiyi1992/ZYCornerRadius#15]
你好，源码中使用了方法交换：
[self.class swizzleMethod:@selector(layoutSubviews) anotherMethod:@selector(zy_LayoutSubviews)];

可以不使用方法交换实现吗？毕竟方法交换太危险，应当尽量避免使用。

**Comment by liuzhiyi1992** [comment]
恩，swizzle的确是比较危险，但是控制得当时没有问题的，ZYCornerRadius在特定情况下才会触发swizzle特定的Method，在swizzleMethod里还有对应的条件判断，容错性是足够的
