### ISSUE TITLE
version 0.9.4 crash

### ISSUE THREAD

**Issue by feideperson** [liuzhiyi1992/ZYCornerRadius#16]
Crash at KVO method but version 0.9.3 works well.

**Comment by liuzhiyi1992** [comment]
used some autoLayout Framework?  Masonry ? can you get me the Log, and crash for what scene?  i cant touch off it.

**Comment by feideperson** [comment]
Yes, I do use Masonry. I find the crash point that the ViewController having rounded UIImageView dealloc. The following is the log.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x14f06b3f0 of class UIImageView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x14f0678d0> (
<NSKeyValueObservance 0x14f03b640: Observer: 0x14f06b3f0, Key path: image, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x14deb7150>
)'

**Comment by liuzhiyi1992** [comment]
can you get me a Demo?  I trying for a long time and can not touch off it.     : (

**Comment by liuzhiyi1992** [comment]
[ZYCornerRadius-master 3.zip](https://github.com/liuzhiyi1992/ZYCornerRadius/files/349074/ZYCornerRadius-master.3.zip)

It is a demo here about using Masonry.

**Comment by feideperson** [comment]
[ZYCornerRadius-master 3.zip](https://github.com/liuzhiyi1992/ZYCornerRadius/files/349139/ZYCornerRadius-master.3.zip)

You can try this modified version.

**Comment by liuzhiyi1992** [comment]
fit! but i cant upload the working well demo here with the terrible network, please update v1.0.1 from pod, thanks for your help!

**Comment by liuzhiyi1992** [comment]
[ZYCornerRadius_3.zip](https://github.com/liuzhiyi1992/ZYCornerRadius/files/353428/ZYCornerRadius_3.zip)
