### ISSUE TITLE
使用SDWebImage的情况下，滑动UITableView会存在闪烁的情况

### ISSUE THREAD

**Issue by ozygod** [liuzhiyi1992/ZYCornerRadius#17]
如题，我试过不使用SDWebImage网络加载图片的话，滑动不会闪烁，能否请教下，在使用SDWebImage的情况下，要怎么裁圆角才不会滑动闪烁

**Comment by ozygod** [comment]
我直接在Completed block里裁图片处理了，- -

**Comment by liuzhiyi1992** [comment]
是圆角闪烁还是图片闪烁？网络延迟情况会造成图片闪烁，应添加placeholder

**Comment by ozygod** [comment]
貌似是图片闪烁，会让UITableView顿卡一下，但是去掉加载网络图片的代码就正常，网络不延迟，我添加过placeholder的，闪烁情况只会出现在有网络图片的情况下

**Comment by liuzhiyi1992** [comment]
在初始化的时候配置好圆角，后面使用sd_setImageWithUrl:等API设置网络图片？
UITableView卡顿问题是否是没有重用cell造成呢？

**Comment by ozygod** [comment]
重用的，因为问题只出在使用sd_setImageWithUrl，并且url不为空的时候，如果，url都是空的，也不会出现闪烁和卡顿

**Comment by liuzhiyi1992** [comment]
是最新版本的问题吗，如果图片闪烁不是placeholder——>image的闪烁的话，可否提供个demo，因为这边目前没有发现这样的问题

**Comment by ozygod** [comment]
是1.0.1，demo的话，需要过两天，这个问题是在我项目中出现的

**Comment by liuzhiyi1992** [comment]
@ozygod 我这边也尝试验证下 : )
