### ISSUE TITLE
希望能够加一个UIView的Category

### ISSUE THREAD

**Issue by robert1202** [liuzhiyi1992/ZYCornerRadius#2]
希望能够加一个UIView的Category，ths

**Comment by liuzhiyi1992** [comment]
一般没有往UIView里放图片，朋友切角是为了解决什么情况的问题呢？

**Comment by ShaochongDu** [comment]
学习了原理，太感谢了。不过我也建议加下view 和 button来处理，比如：https://github.com/CoderJackyHuang/HYBImageCliped 这个人写的，但是感觉没你写的简单明了，而且有文章解释。

**Comment by liuzhiyi1992** [comment]
不谢哈，可观评价来说，其实标哥的用起来不太方便不够智能，也有很多冗余的地方，功能广度大些可是深度还差点。

其实view的切角直接使用cornerRadius就可以了，不会触发离屏，朋友是希望我对UIView的什么情况作出处理呢？

**Comment by ShaochongDu** [comment]
UIView和UIButton 这些设置圆角跟UIImageView的原理不一样吗，不会触发离屏渲染？

**Comment by ShaochongDu** [comment]
他们也是通过 
imageView.layer.cornerRadius = CGFloat(10);  
imageView.layer.masksToBounds = YES;  
这两个属性进行设置的啊。还请指点。

**Comment by liuzhiyi1992** [comment]
单纯使用cornerRadius并不会触发离屏，元凶在于使用masksToBounds去切掉imageView的content，因为UIView一般不用来承载图片，仅仅是对含backgroundColor的UIView切角直接使用cornerRadius即可，同理不含图片的UIButton也是的，但是如果为UIButton设置backgroundImage就必须用到masksToBounds切角，这时才会触发离屏。

一般用UIView或者UIButton承载图片的情况比较少

**Comment by ShaochongDu** [comment]
嗯 多谢指教

发自我的 iPhone

**Comment by ShaochongDu** [comment]
今天试了一个demo发现，还不如系统的layer效率高呢，使用zy_cornerRadiusAdvance这种明显卡顿在真机上，不知道是不是因为我使用xib的原因，我是在tableview的cell上放的imageview然后在awakeFromNib中使用的[self.imgView zy_cornerRadiusAdvance:5.0 rectCornerType:UIRectCornerAllCorners]方法，不知道是不是复用机制的问题

**Comment by liuzhiyi1992** [comment]
然后朋友的demo会出现卡顿？我的demo是300个圆角，每个cell20个，每次updateCell都做一次setImage，暂时没发现会有卡顿，性能数据也非常正常

**Comment by ShaochongDu** [comment]
你qq多少  我发给你demo  我qq 1183599228
