### ISSUE TITLE
如果只是设置背景颜色，无法切圆角

### ISSUE THREAD

**Issue by guanghua07** [liuzhiyi1992/ZYCornerRadius#20]

**Comment by liuzhiyi1992** [comment]
@guanghua07  只是设置背景图片具体是什么意思？

**Comment by SenorSamuel** [comment]
我也遇到了相同的问题, 如果我只要想切圆角, 不设置图片, 按照demo设置,无法切圆角

**Comment by liuzhiyi1992** [comment]
@guanghua07 @SenorSamuel 
不需要设图片的话，基本不需要用到这个库，直接为imageView的layer做setCornerRadius即可，因为不需要masksToBounds，所以不会触发离屏渲染
