### ISSUE TITLE
collectionView第一屏显示问题

### ISSUE THREAD

**Issue by demoker** [liuzhiyi1992/ZYCornerRadius#25]
第一次加载出来的时候，第一屏的图片大小偏小于ImageView本身，两边留有空白，而且圆角也存在问题，只有左上角有圆角，滚动之后就好了，请问这是什么问题？ @liuzhiyi1992

**Comment by liuzhiyi1992** [comment]
Xcode8？CornerRadius版本号是？

**Comment by liuzhiyi1992** [comment]
@demoker

**Comment by demoker** [comment]
Xcode8  当前版本：1.0.2

**Comment by liuzhiyi1992** [comment]
在setImage之前，调用[imageview layoutIfNeeded]试试,
是Masonry布局还是IBAutolayout呢?

**Comment by demoker** [comment]
xib

**Comment by demoker** [comment]
使用的xib，朋友，调用[imageview layoutIfNeeded]不行，方便qq吗？这边给你截图 本人q909352358
UIImageView的约束是没有问题的，就单纯是图片显示的问题，刷新之后就好了，很奇怪

**Comment by liuzhiyi1992** [comment]
ok稍等
