### ISSUE TITLE
为何不在子线程切圆角

### ISSUE THREAD

**Issue by ghost** [liuzhiyi1992/ZYCornerRadius#27]
在大量圆角的view 明显感觉到卡顿 像sdwebimage那样 框架内部异步处理好点

**Comment by liuzhiyi1992** [comment]
@xuejianlan55  子线程切角会有不及时的问题，tableView滑动会有明显的闪动，布局正确的情况下大量圆角会已经排除离屏和内存问题(屏幕内150圆角图片内存无上涨)，可能是有其他的因素影响
