### ISSUE TITLE
关于layoutsubviews触发的疑问

### ISSUE THREAD

**Issue by xdkhan** [liuzhiyi1992/ZYCornerRadius#3]
你好，我看到你在博客里写了原理。当一个UI image view设置frame时才会触发layoutsubviews方法或者swizzingmethod改变的方法。当使用sdwebimage时，首先设置一个placeholder图片，然后走了那个方法。过了一会儿网络请求的图片被赋给了image view，此时会触发layoutsubviews方法吗？

**Comment by liuzhiyi1992** [comment]
是的，除了改变尺寸或者addSubview外都不能触发，这只能适用于先设置好图片 和 网络比较快的 sd_setImage， 我文章在swizzingmethod之后有讲到使用KVO保证图片处理持续有效的做法，可能这篇博文把所有研究过程的记录式地写下来的确是有点乱。

抱歉那么晚回复，放假刚赶回来
