### ISSUE TITLE
非常不错，但是有一些需求需要设置个别圆角 希望作者增加四个圆角的设定是否展示的api

### ISSUE THREAD

**Issue by wuyangchinanju** [liuzhiyi1992/ZYCornerRadius#4]

**Comment by liuzhiyi1992** [comment]
- (instancetype)initWithCornerRadiusAdvance:(CGFloat)cornerRadius rectCornerType:(UIRectCorner)rectCornerType;
- (void)zy_cornerRadiusAdvance:(CGFloat)cornerRadius rectCornerType:(UIRectCorner)rectCornerType;

后面可以带UIRectCorner参数，指定圆角位置
