### ISSUE TITLE
设置圆角后再使用SD加载网络图片的时候崩溃

### ISSUE THREAD

**Issue by luo-h** [liuzhiyi1992/ZYCornerRadius#41]
UIGraphicsBeginImageContextWithOptions(size, NO, scale);

scanle = 2

**Comment by luo-h** [comment]
我是给btn.imageView设置的圆角和边框，如果直接给btn setImage不会崩溃，如果给btn加载网络图片就会崩溃

**Comment by applekwork** [comment]
崩溃到哪了呢？
