### ISSUE TITLE
图片闪动

### ISSUE THREAD

**Issue by liuhy412484577** [liuzhiyi1992/ZYCornerRadius#5]
tableview 刷新的时候会有闪动情况，怎么处理？

**Comment by liuzhiyi1992** [comment]
更新0.8.1可解决此问题 : )

**Comment by liuhy412484577** [comment]
8.1的更新不下来，pod 报错，还没更新嘛？

**Comment by liuzhiyi1992** [comment]
ok了，换了个网络才更上去

**Comment by liuzhiyi1992** [comment]
pod search ZYCornerRadius可以查看相关的版本号

**Comment by liuhy412484577** [comment]
为啥我这还是0.7.1 ？／

**Comment by liuzhiyi1992** [comment]
pod search 出来最高版本是7.1吗

**Comment by liuhy412484577** [comment]
嗯 
-> ZYCornerRadius (0.7.1)
   A Category to make cornerRadius for UIImageView have no Offscreen-Rendered,
   be more efficiency.
   pod 'ZYCornerRadius', '~> 0.7.1'
- Homepage: https://github.com/liuzhiyi1992/ZYCornerRadius
- Source:   https://github.com/liuzhiyi1992/ZYCornerRadius.git
- Versions: 0.7.1, 0.6.1, 0.5.1, 0.4.1, 0.3.1 [master repo]
  RRLhydeMacBook-Pro:~ rrlhy$

**Comment by liuzhiyi1992** [comment]
难道pod有延迟。。。我这边

-> ZYCornerRadius (0.8.1)
   A Category to make cornerRadius for UIImageView have no Offscreen-Rendered,
   be more efficiency.
   pod 'ZYCornerRadius', '~> 0.8.1'
- Homepage: https://github.com/liuzhiyi1992/ZYCornerRadius
- Source:   https://github.com/liuzhiyi1992/ZYCornerRadius.git
- Versions: 0.8.1, 0.7.1, 0.6.1, 0.5.1, 0.4.1, 0.3.1 [master repo]

如果直接update不行，或者晚点再试试

**Comment by liuhy412484577** [comment]
你那边已经有了是吧？那我等等再看看

**Comment by liuhy412484577** [comment]
好的，谢谢！

**Comment by liuhy412484577** [comment]
我这边现在更新了0.8.1 有个问题就是tableview 设置圆角，容易爆内存警告，卡死
怎么回事？

**Comment by liuzhiyi1992** [comment]
使用category的方式吗？检查下是否忘记设置Cell的重用标识

**Comment by liuhy412484577** [comment]
用的是category cell的从用标识符有的

**Comment by liuzhiyi1992** [comment]
刚开完会，造成内存暴增的动作是怎样的？在一个区域内来回滑动tableview，还是一直往下滑动tableview？

**Comment by liuhy412484577** [comment]
一直往下滑动，真机上很快就崩掉了，模拟器上还好

**Comment by liuzhiyi1992** [comment]
是demo还是项目内？demo的话可以发给我debug下

**Comment by liuhy412484577** [comment]
我在项目pod你的库的

**Comment by liuzhiyi1992** [comment]
可否debug下cell是否有实现重用？之前有位朋友出现过这样的问题

**Comment by liuhy412484577** [comment]
好的，我查查看！
