### ISSUE TITLE
pod上面没有最新版本

### ISSUE THREAD

**Issue by findM** [liuzhiyi1992/ZYCornerRadius#7]
![Uploading 0746EECE-898F-4C64-A14B-D79A49AB1686.png…]()
pod上面没有最新版本

**Comment by liuzhiyi1992** [comment]
pod上最新版本为0.8.1，朋友那边不是吗
<img width="553" alt="35bf4ed6-8924-458c-bf21-130adc8b02af" src="https://cloud.githubusercontent.com/assets/13046550/14640280/66e93474-0673-11e6-8a50-a9eea53f31cc.png">

**Comment by findM** [comment]
我的不是，是因为我是用 淘宝镜像服务器的原因吗

**Comment by liuzhiyi1992** [comment]
我也是淘宝源，朋友你那边看见最高版本是多少？

**Comment by liuzhiyi1992** [comment]
搜索不到最新版本的库，应该将pod更新到最新版本可以解决。我这边的pod --version是0.39.0  

重新做一次升级安装：
$ sudo gem update --system
$ gem sources --remove https://rubygems.org/ 
$ gem sources -a http://ruby.taobao.org/ 
$ sudo gem install cocoapods
$ pod setup

**Comment by findM** [comment]
![图](http://7u2lyw.com1.z0.glb.clouddn.com/470C72AC-1535-4E1D-8F43-03EDA29EA9FA.png)
不知道为什么，我的一直是这样的

**Comment by liuzhiyi1992** [comment]
其他设备会这样吗？我这边另外一台电脑也可以搜到

**Comment by liuzhiyi1992** [comment]
直接在项目podFile里改掉版本号，再pod update试试呢

**Comment by liuzhiyi1992** [comment]
如果项目内都update不下来，还是建议试试升级pod，或者现在有更高的版本
